# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  todoapp-server:
    image: todoapp-server
    container_name: TodoApp.Server
    build:
      context: .
      dockerfile: TodoApp.Server/Dockerfile.debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./:/src
