# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  todoapp-server:
    image: todoapp-server
    container_name: TodoApp.Server
    build:
      context: .
      dockerfile: TodoApp.Server/Dockerfile.debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./:/src
    depends_on:
      - pg-db
    networks:
      - backend

  pg-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SimplePassword1
    networks:
      - backend
    logging:
      driver: none

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@backend.com
      PGADMIN_DEFAULT_PASSWORD: SimplePassword1
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - pg-db
    logging:
      driver: none

networks:
  backend:
    
