/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type createB = {
    createBoard: {
        isSuccessfull: boolean;
    };
};
export type createBVariables = {
    title: string;
};
