/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type showBoard = {
    board: ({
        id: string;
        title: string;
        description: string | null;
        creationDate: any;
    }) | null;
};
export type showBoardVariables = {
    id: string | null;
};
