version: "3.8"

services:
  todoapp-proxy:
    container_name: Dev.TodoApp.Proxy
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/certs:/etc/ssl/private
    networks:
      - todoapp-internal-dev
    depends_on:
      - todoapp-client
      - todoapp-server
      - todoapp-pgadmin

  todoapp-client:
    container_name: Dev.TodoApp.Client
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./frontend:/app
    networks:
      - todoapp-internal-dev

  todoapp-server:
    container_name: Dev.TodoApp.Server
    build:
      context: ./backend
      dockerfile: ./TodoApp.Server/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MAIN_DB_CONNECTION_STRING=Host=todoapp-database;Database=todo_app;Username=admin;Password=SimplePassword1;
    volumes:
      - ./backend:/src
    networks:
      - todoapp-internal-dev

  todoapp-database:
    container_name: Dev.TodoApp.Database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SimplePassword1
    volumes:
      - todoapp-database-dev:/var/lib/postgresql/data
    networks:
      - todoapp-internal-dev

  todoapp-pgadmin:
    container_name: Dev.TodoApp.PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@backend.com
      PGADMIN_DEFAULT_PASSWORD: SimplePassword1
    networks:
      - todoapp-internal-dev
    volumes:
      - todoapp-pgadmin-dev:/var/lib/pgadmin

networks:
  todoapp-internal-dev:
    name: Dev.TodoApp.Internal

volumes:
  todoapp-database-dev:
    name: Dev.TodoApp.Database
  todoapp-pgadmin-dev:
    name: Dev.TodoApp.PgAdmin
