version: "3.8"

services:
  todoapp-client:
    container_name: TodoApp.Client
    image: todoapp-client
    depends_on:
      - todoapp-server

  todoapp-server:
    container_name: TodoApp.Server
    image: todoapp-server
    depends_on:
      - todoapp-database

  todoapp-database:
    container_name: TodoApp.Database
    image: postgres

  todoapp-pgadmin:
    container_name: TodoApp.PgAdmin
    image: dpage/pgadmin4
    depends_on:
      - todoapp-database
