name: Count lines of code

on:
  workflow_dispatch:

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Count Lines of Code
      uses: djdefi/cloc-action@2
    
    - name: Upload cloc output as a build artifact
      uses: actions/upload-artifact@v1
      with:
        name: cloc
        path: cloc.txt
